name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy to Raspberry Pi
        run: |
          scp -r -P 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null C:\Users\ignac\Desktop\Full Stack Projects\DesafioTecnicoLazarillo\dist/desafio-tecnico-lazarillo/browser user@192.168.1.85:/home/***/Desktop/tech-challenge
        
