name: Deploy to ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using reusable action
        uses: ./.github/actions/deploy_ubuntu/