name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.RPI_HOST }}
            username: ${{ secrets.RPI_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.RPI_PORT }}
            script: |
              ssh nacho@192.168.1.85 'rm -rf /home/nacho/Desktop/tech-challenge/build'
              scp -r C:\Users\ignac\Desktop\Full Stack Projects\DesafioTecnicoLazarillo\build nacho@192.168.1.85:/home/nacho/Desktop/tech-challenge
        
