name: Deploy to ubuntu

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy using reusable action
        uses: ./.github/actions/deploy_ubuntu/