name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies & build
        run: |
          npm install  # Or the command to install your dependencies
          npm run build # Or the command to build your project

      - name: List files in the runner
        run: ls -al

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.1.85
          username: nacho
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            scp -r ~/dist nacho@192.168.1.85/home/nacho/
