name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/workflows/deploy_ubuntu.yml